apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: go-server:latest
        imagePullPolicy: Never  # pull localy only
        ports:
        - containerPort: 9090
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: go-server-secret
              key: password
        resources:
          requests:
            memory: "100Mi"
            cpu: 0.1
          limits:
            memory: "200Mi"
            cpu: 0.2
---
apiVersion: v1
kind: Service
metadata:
  name: go-server
spec:
  type: LoadBalancer # enable access from the internet
  selector:
    app: go-server
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-server-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - myapp.local
    secretName: my-tls-secret
  rules:
  - host: myapp.local
    http:
      paths:
      - path: /api/v1/music-albums
        pathType: Prefix
        backend:
          service:
            name: go-server
            port:
              number: 80