# as builder allows as coping artifacts from it to later stage
FROM golang:1.24-alpine as builder

WORKDIR /app
COPY . .

RUN go build -o server .

FROM alpine:latest

# Install redis
RUN apk add --no-cache redis

WORKDIR /app
# copy from previuse stage the articates to our new image
COPY --from=builder /app/server .

CMD ["./server", "redis-server:6379", "$PASSWORD"]