FROM golang:1.24-alpine as builder

WORKDIR /app
COPY . .

RUN go build -o server .

FROM alpine:latest

RUN apk add --no-cache redis

WORKDIR /app
COPY --from=builder /app/server .

CMD ["./server", "redis-server:6379", "$PASSWORD"]